### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Bin-ze** [Fediory/HVI-CIDNet#36]
First of all, thank you very much for your open source！

I wanted to test the generalization of this method on other data, so I collected a set of surveillance frames and tried to use the pre-trained weights for inference, but I got poor quality enhancements. 

<img width="828" alt="image" src="https://github.com/user-attachments/assets/856ab3c1-679f-45f4-8cb7-7b98b8d979d0">

Left: Enhanced Right: No Enhanced

I want to know if this method must reconstruct pairs in its own scene for training.

**Comment by Fediory** [comment]
Did try all the types of weights? Is all the weights output a bad result?

**Comment by Bin-ze** [comment]
I tried all the weights, and tried adjusting the alpha factor. I wonder what the alpha factor does: does it indicate the light intensity mix ratio?

this is my result:

<img width="1644" alt="image" src="https://github.com/user-attachments/assets/2d020285-c32d-4741-b507-8b04091d15c9">

Results from several different network weights

The algorithm can indeed improve the exposure of the scene, but from my observation, it does not improve the noise caused by brightening, and even appears to be more noisy, and also shows some color cast.

I have just entered this field, so there are many theoretical knowledge that is not solid.

I want to know, in my scene (surveillance camera), can I improve this problem by fine-tuning by constructing pairs of images?

In addition, can the algorithm suppress the problem caused by large light ratio at night (as shown in the example image)? The current visualization results show that the algorithm tends to increase the brightness of all positions at the same time (similar to increasing image exposure).

Your valuable reply is very valuable! Thank you!

**Comment by Fediory** [comment]
Q1:  Is the alpha factor does: does it indicate the light intensity mix ratio?
A1: Yes. High alpha factor indicate high illuminance as light intensity.

Q2: Why this scene have a bad enhancement result?
A2: The model we trained were only on LOL based dataset and Sony Total Dark. It is possible that your camera (sensor) is different than those datasets. 

Q3: Can I improve this problem by fine-tuning by constructing pairs of images?
A3: Yes, you can try to solve it in several ways as follows. 
1. Adobe PS was used to reduce the brightness of the image and a LOLv1 or LOLv2-real trained model was used to enhance this photo.
2. Modify the three parameters in HVI space and the T(x) equation to go ahead and modify the noise and low-light degradation distributions in your image to the distributions provided in our paper for the dataset.
3. Build a low-light dataset based on your camera and retrain the model.

Q4: In addition, can the algorithm suppress the problem caused by large light ratio at night (as shown in the example image)?
A4: I think yes, but its generalization ability has only been verified on LOL-related datasets so far, and still needs further testing on other photos.

**Comment by Fediory** [comment]
https://huggingface.co/spaces/Fediory/HVI-CIDNet_Low-light-Image-Enhancement_
We've uploaded the model demo to the hugging face website, where you can test it to see if it solves the generalizability problem you've raised.
